apiVersion: v1
kind: Service
metadata:
  name: proxysql
  labels:
    app: proxysql
spec:
  type: ClusterIP
  ports:
    - port: 6032
      protocol: TCP
      name: sql
    - port: 6033
      protocol: TCP
      name: admin
  selector:
    app: proxysql