apiVersion: batch/v1beta1
kind: CronJob

metadata:
  name: proxysql-sync-default-hostgroup

spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: proxysql-sync-default-hostgroup
              image: "scienta/k8s-proxysql-cluster:1.2.1"
              imagePullPolicy: Always
              args: ["--sync_default_hostgroup"]

              env:
                - name: PROXYSQL_SERVICE
                  value: proxysql-test
                - name: MYSQL_ADMIN_USERNAME
                  value: db_manager
                - name: MYSQL_ADMIN_PASSWORD
                  value: secretpassword
                - name: PROXYSQL_ADMIN_USERNAME
                  value: proxysql-admin
                - name: PROXYSQL_ADMIN_PASSWORD
                  value: adminpassw0rd

              volumeMounts:
                - mountPath: /etc/proxysql.cnf
                  name: proxysql
                  subPath: proxysql.cnf

          volumes:
            - name: proxysql
              configMap:
                name: proxysql
                defaultMode: 0777
